#!/bin/bash
FOLDER="/root/ROMANIS"

scp $FOLDER/Apps/acquire_app.conf 192.168.0.10:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 
scp $FOLDER/Apps/acquire_app.conf 192.168.0.11:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 
scp $FOLDER/Apps/acquire_app.conf 192.168.0.12:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 
scp $FOLDER/Apps/acquire_app.conf 192.168.0.13:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 

scp $FOLDER/Apps/acquire_app.conf 192.168.10.10:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 
scp $FOLDER/Apps/acquire_app.conf 192.168.10.11:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 
scp $FOLDER/Apps/acquire_app.conf 192.168.10.12:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 
scp $FOLDER/Apps/acquire_app.conf 192.168.10.13:/usr/src/linux/drivers/16ai64ssa/acquire_app/

scp $FOLDER/Apps/acquire_app_int.conf 192.168.0.10:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 
scp $FOLDER/Apps/acquire_app_int.conf 192.168.0.11:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 
scp $FOLDER/Apps/acquire_app_int.conf 192.168.0.12:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 
scp $FOLDER/Apps/acquire_app_int.conf 192.168.0.13:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 

scp $FOLDER/Apps/acquire_app_int.conf 192.168.10.10:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 
scp $FOLDER/Apps/acquire_app_int.conf 192.168.10.11:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 
scp $FOLDER/Apps/acquire_app_int.conf 192.168.10.12:/usr/src/linux/drivers/16ai64ssa/acquire_app/ 
scp $FOLDER/Apps/acquire_app_int.conf 192.168.10.13:/usr/src/linux/drivers/16ai64ssa/acquire_app/  

echo "Config File Updated in DAQs"

echo -e "Update TinyCore boot-image as well? (y/n): \c"
read reply
if [ $reply == y ]; then
	cp -a $FOLDER/Apps/acquire_app.conf $FOLDER/TCLINUX_INITRD/extract/usr/local/src/linux*/drivers/16ai64ssa/acquire_app/
	cp -a $FOLDER/Apps/acquire_app_int.conf $FOLDER/TCLINUX_INITRD/extract/usr/local/src/linux*/drivers/16ai64ssa/acquire_app/
	$FOLDER/DAQ_scripts/update_tinycore_img

else
	echo -e "\nTinyCore boot-image NOT updated\n"
	exit 
fi
