#!/bin/bash
sshpass -proot ssh root@192.168.0.10 'reboot'
sshpass -proot ssh root@192.168.0.11 'reboot'
sshpass -proot ssh root@192.168.0.12 'reboot'
sshpass -proot ssh root@192.168.0.13 'reboot'

sshpass -proot ssh root@192.168.10.10 'reboot'
sshpass -proot ssh root@192.168.10.11 'reboot'
sshpass -proot ssh root@192.168.10.12 'reboot'
sshpass -proot ssh root@192.168.10.13 'reboot'

